// ═══════════════════════════════════════════════
// LACA TV — Static Data & Constants
// ═══════════════════════════════════════════════

export const MOCK_VIDEOS = [
  {
    id: 1,
    title: "Real Madrid 4-3 Man City — All Goals & Highlights",
    league: "Champions League",
    leagueFlag: "🏆",
    duration: "14:22",
    views: 128000,
    uploadedAt: "2026-04-10T10:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Incredible Champions League semi-final with 7 goals! Real Madrid edge out Man City in a thriller at the Bernabeu. Vinicius Jr. with a stunning brace.",
    tags: ["Real Madrid", "Man City", "Champions League"],
    featured: true,
    isNew: true,
    bgGrad: "135deg,#0a2e18,#1a5e32",
  },
  {
    id: 2,
    title: "Arsenal 2-1 Tottenham — North London Derby Highlights",
    league: "Premier League",
    leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    duration: "8:24",
    views: 84000,
    uploadedAt: "2026-04-09T08:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Arsenal claim derby bragging rights with a late winner from Saka. Controversial VAR moment in the second half changes the game.",
    tags: ["Arsenal", "Tottenham", "Premier League"],
    featured: false,
    isNew: true,
    bgGrad: "135deg,#1a0a2e,#2e1a5e",
  },
  {
    id: 3,
    title: "Barcelona 4-2 Atletico Madrid — Extended Highlights",
    league: "La Liga",
    leagueFlag: "🇪🇸",
    duration: "10:05",
    views: 56000,
    uploadedAt: "2026-04-08T20:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "El Clasico del Atletico ends 4-2. Lewandowski hat-trick in a stunning comeback display at the Camp Nou.",
    tags: ["Barcelona", "Atletico Madrid", "La Liga"],
    featured: false,
    isNew: false,
    bgGrad: "135deg,#2e0a0a,#5e1a0d",
  },
  {
    id: 4,
    title: "Bayern Munich 3-2 Dortmund — Der Klassiker Full Highlights",
    league: "Bundesliga",
    leagueFlag: "🇩🇪",
    duration: "11:05",
    views: 72000,
    uploadedAt: "2026-04-08T18:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Bayern snatch a late winner to claim all three points. Kane hat-trick leads the comeback from 2-0 down.",
    tags: ["Bayern Munich", "Dortmund", "Bundesliga"],
    featured: false,
    isNew: true,
    bgGrad: "135deg,#1a1400,#3d2e00",
  },
  {
    id: 5,
    title: "Nigeria vs South Africa — AFCON 2025 Quarter Final",
    league: "AFCON",
    leagueFlag: "🌍",
    duration: "6:12",
    views: 210000,
    uploadedAt: "2026-04-07T16:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Super Eagles dominate to reach the AFCON semi-finals. Osimhen hat-trick lights up the tournament in front of 80,000 fans.",
    tags: ["Nigeria", "South Africa", "AFCON", "Super Eagles"],
    featured: false,
    isNew: false,
    bgGrad: "135deg,#002200,#004d00",
  },
  {
    id: 6,
    title: "Inter Milan 3-1 AC Milan — Derby Della Madonnina",
    league: "Serie A",
    leagueFlag: "🇮🇹",
    duration: "7:33",
    views: 143000,
    uploadedAt: "2026-04-07T15:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Inter Milan thrash city rivals in a dominant display. Lautaro Martinez with a brace in front of a sold-out San Siro.",
    tags: ["Inter Milan", "AC Milan", "Serie A"],
    featured: false,
    isNew: false,
    bgGrad: "135deg,#001a3d,#003080",
  },
  {
    id: 7,
    title: "Enyimba FC vs Rivers United — NPFL Matchday 22",
    league: "NPFL",
    leagueFlag: "🇳🇬",
    duration: "5:58",
    views: 18000,
    uploadedAt: "2026-04-10T12:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Enyimba FC claim a crucial three points at home in the NPFL title race. Late goal seals a hard-fought win.",
    tags: ["Enyimba", "Rivers United", "NPFL", "Nigeria"],
    featured: false,
    isNew: true,
    bgGrad: "135deg,#1a2200,#334400",
  },
  {
    id: 8,
    title: "Man United 0-2 Liverpool — Premier League Highlights",
    league: "Premier League",
    leagueFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    duration: "10:20",
    views: 389000,
    uploadedAt: "2026-04-06T17:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Liverpool ease past United at Old Trafford. Salah and Nunez on target as the Reds extend their lead at the top.",
    tags: ["Manchester United", "Liverpool", "Premier League"],
    featured: false,
    isNew: false,
    bgGrad: "135deg,#1a0010,#3d0025",
  },
  {
    id: 9,
    title: "PSG 2-0 Juventus — UCL Quarter Final Highlights",
    league: "Champions League",
    leagueFlag: "🏆",
    duration: "9:47",
    views: 95000,
    uploadedAt: "2026-04-05T21:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "PSG control the tie with a professional display at Parc des Princes. Mbappé and Dembélé on target.",
    tags: ["PSG", "Juventus", "Champions League"],
    featured: false,
    isNew: false,
    bgGrad: "135deg,#1a003d,#2e0060",
  },
  {
    id: 10,
    title: "Kano Pillars vs Plateau United — NPFL Highlights",
    league: "NPFL",
    leagueFlag: "🇳🇬",
    duration: "5:20",
    views: 12000,
    uploadedAt: "2026-04-05T14:00:00Z",
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    description: "Kano Pillars bounce back with a vital home win. Exciting end-to-end football in the NPFL midseason clash.",
    tags: ["Kano Pillars", "Plateau United", "NPFL"],
    featured: false,
    isNew: false,
    bgGrad: "135deg,#2e1100,#5e2500",
  },
];

export const LEAGUES = [
  "All",
  "Premier League",
  "La Liga",
  "Champions League",
  "Bundesliga",
  "Serie A",
  "AFCON",
  "NPFL",
  "Ligue 1",
  "Europa League",
];

export const LEAGUE_META = {
  "Premier League":   { flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", color: "#6c2eb9" },
  "La Liga":          { flag: "🇪🇸", color: "#c0392b" },
  "Champions League": { flag: "🏆", color: "#1a6baf" },
  "Bundesliga":       { flag: "🇩🇪", color: "#b8990a" },
  "Serie A":          { flag: "🇮🇹", color: "#014099" },
  "AFCON":            { flag: "🌍", color: "#1a7a3c" },
  "NPFL":             { flag: "🇳🇬", color: "#008751" },
  "Ligue 1":          { flag: "🇫🇷", color: "#1a4fa8" },
  "Europa League":    { flag: "🏅", color: "#e8531a" },
};

export const INIT_SCORES = [
  { id:1, league:"EPL",        home:"Arsenal",     away:"Tottenham",  score:"2-1", minute:90, live:false },
  { id:2, league:"La Liga",    home:"Barcelona",   away:"Atletico",   score:"1-1", minute:67, live:true  },
  { id:3, league:"UCL",        home:"Real Madrid", away:"Man City",   score:"4-3", minute:90, live:false },
  { id:4, league:"Bundesliga", home:"Bayern",      away:"Dortmund",   score:"3-2", minute:90, live:false },
  { id:5, league:"Serie A",    home:"Inter",       away:"AC Milan",   score:"3-1", minute:90, live:false },
  { id:6, league:"Ligue 1",    home:"PSG",         away:"Marseille",  score:"2-0", minute:78, live:true  },
  { id:7, league:"NPFL",       home:"Enyimba",     away:"Rivers Utd", score:"1-0", minute:90, live:false },
  { id:8, league:"EPL",        home:"Chelsea",     away:"Man City",   score:"0-2", minute:45, live:true  },
  { id:9, league:"UCL",        home:"PSG",         away:"Juventus",   score:"1-0", minute:90, live:false },
  { id:10,league:"La Liga",    home:"Real Madrid", away:"Sevilla",    score:"3-0", minute:90, live:false },
];

export const BG_GRADS = [
  { label: "Forest",  value: "135deg,#0a2e18,#1a5e32" },
  { label: "Navy",    value: "135deg,#0a0e2e,#1a1e5e" },
  { label: "Claret",  value: "135deg,#2e0a0a,#5e1010" },
  { label: "Teal",    value: "135deg,#0a2a2e,#1a5a5e" },
  { label: "Purple",  value: "135deg,#1a0a2e,#2e1a5e" },
  { label: "Steel",   value: "135deg,#0a1a2e,#1a3a5e" },
  { label: "Amber",   value: "135deg,#1a1200,#3d2c00" },
  { label: "Olive",   value: "135deg,#1a2200,#334400" },
];

// Admin password — change before going live
export const ADMIN_PASSWORD = "lacatv2026";
